openapi: 3.0.1
info:
  title: Hello World
  description: Just say hello to the world.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /hello/{name}:
    get:
      operationId: sayHello
      summary: Say hello to the user
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: The name of the user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sayHelloResponse'

components:
  schemas:
    sayHelloResponse:
      type: object
      properties:
        hello:
          type: string
          description: Hello to the user

